// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Clientes
{
    // IdCliente es INT IDENTITY en la BD (ver SistemaOpinionCliente - 2025-1121.sql).
    // Antes se declaraba como string/varchar(6) por error (mezclado con el esquema
    // homologado de la BD analítica), lo que producía InvalidCastException al leer
    // la columna con EF Core.
    public int IdCliente { get; set; }

    public string Nombre { get; set; } = null!;

    public string Email { get; set; } = null!;

    public virtual ICollection<Opiniones> Opiniones { get; set; } = new List<Opiniones>();
}
