// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Opiniones
{
    public int IdOpinion { get; set; }

    public DateTime? Fecha { get; set; }

    public string? Clasificacion { get; set; }

    public string? Fuente { get; set; }

    // IdCliente/IdProducto son INT en la BD (Clientes/Productos son INT IDENTITY);
    // antes se declaraban como string por error, lo que rompía las lecturas por EF Core.
    public int? IdCliente { get; set; }

    public int? IdProducto { get; set; }

    public virtual Clientes? IdClienteNavigation { get; set; }

    public virtual Productos? IdProductoNavigation { get; set; }
}