// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Productos
{
    // IdProducto es INT IDENTITY en la BD (ver SistemaOpinionCliente - 2025-1121.sql).
    // Antes se declaraba como string por error; causaba InvalidCastException al leer
    // la columna con EF Core.
    public int IdProducto { get; set; }

    public string Nombre { get; set; } = null!;

    public int IdCategoria { get; set; }

    public virtual Categorias? IdCategoriaNavigation { get; set; }

    public virtual ICollection<Opiniones> Opiniones { get; set; } = new List<Opiniones>();
}
